# action.yml
name: "LinearB test release detection action"
description: "Send a http request to the LinearB API to detect the release of a new version of the application"
branding:
  icon: 'bell'  
  color: 'green'
inputs:
  linearb_api_token: # id of input
    description: "API token for LinearB"
    required: true
  release_commit_sha: # id of input
    description: "SHA of the commit to detect the release of"
    required: true
  repository_name: # id of input
    description: "Name of the repository"
    required: true
runs:
  using: "composite"
  steps:
    - id: date
      run: echo "::set-output name=date::$(date +'%s')"
      shell: bash
    - run: |
        curl -X POST --header 'x-api-key: ${{ inputs.linearb_api_token }}' --header 'Content-Type: application/json' -d '{"head_sha": "${{ inputs.release_commit_sha }}", "repo_url": "https://github.com/${{ inputs.repository_name }}.git", "stage_id": "release", "event_time": "${{ steps.date.outputs.date }}"}' https://public-api.linearb.io/api/v1/cycle-time-stages
      shell: bash


